try:
    rd
except BaseException as error:
    print(error)
